name: Upload Python Package

on:
  release:
    types: [published]
  workflow_dispatch:  # Allow manual triggering

permissions:
  contents: read

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04, macos-14]

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21'
        cache: false
    
    - name: Install build dependencies
      run: |
        python -m pip install --upgrade pip wheel setuptools numpy auditwheel
        if [ "${{ matrix.os }}" = "ubuntu-22.04" ]; then
          sudo apt-get update
          sudo apt-get install -y patchelf
        fi
    
    - name: Build wheel
      run: python -m build --wheel --no-isolation
    
    - name: Repair wheel (Linux)
      if: matrix.os == 'ubuntu-22.04'
      run: |
        mkdir -p wheelhouse
        for whl in dist/*.whl; do
          auditwheel repair "$whl" -w wheelhouse/
        done
    
    - name: Copy wheel (macOS)
      if: matrix.os == 'macos-14'
      run: |
        mkdir -p wheelhouse
        cp dist/*.whl wheelhouse/
    
    - name: Store wheels
      uses: actions/upload-artifact@v4
      with:
        name: wheels-${{ matrix.os }}
        path: wheelhouse/*.whl

  build_sdist:
    name: Build source distribution
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip wheel
        pip install build setuptools numpy
    
    - name: Build sdist
      run: python -m build --sdist --no-isolation
    
    - name: Store sdist
      uses: actions/upload-artifact@v4
      with:
        name: sdist
        path: dist/*.tar.gz

  upload:
    needs: [build_wheels, build_sdist]
    runs-on: ubuntu-22.04
    environment:
      name: pypi
      url: https://pypi.org/p/go-polars
    permissions:
      id-token: write

    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        path: dist
        pattern: wheels-*
        merge-multiple: true
    
    - name: Download sdist
      uses: actions/download-artifact@v4
      with:
        name: sdist
        path: dist
    
    - name: Publish package
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        packages-dir: dist/ 